"""
Django settings for bank_zyx project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v2jgynr!cjgk4rrtmelv$gyixmc+7xcrak)^6u=dio6n1k5b+d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.sysuser', 
    'apps.sysrole', 
    'apps.sysmenu', 
    'apps.sysrolemenu',
    'apps.sysuserrole',
    'apps.announcement',
    'apps.userinfo',
    'apps.tradeinfo',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
    'django_filters',
    'apps.cardinfo',   # 添加
    'corsheaders',  
    'apps.impeachform',
    'apps.audit',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'bank_zyx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bank_zyx.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'zyx',
        'USER': 'root',
        'PASSWORD': '12345678',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'apps/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# docs文档配置
''''
#REST_FRAMEWORK = {
    # 默认使用Django的权限系统
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # 使用JWT作为认证方式
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 接口文档配置
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    # 分页,默认每页10条
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    # 解析器
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    # 搜索参数
    'SEARCH_PARAM': 'search',
    # 过滤后端
    'FILTER_BACKENDS': [
        'rest_framework.filters.DjangoFilterBackend',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

}
'''
# docs文档配置
REST_FRAMEWORK = {
    # 默认使用Django的权限系统
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # 开发阶段允许所有访问
        # 生产环境建议使用：
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    
    # 使用JWT作为认证方式
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # 添加Session认证，用于admin
        'rest_framework.authentication.BasicAuthentication',    # 添加Basic认证
    ),
    
    # 接口文档配置
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    
    # 分页,默认每页10条
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    
    # 解析器 - 必须包含MultiPartParser用于文件上传
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',           # 解析JSON数据
        'rest_framework.parsers.FormParser',           # 解析表单数据
        'rest_framework.parsers.MultiPartParser',      # 解析multipart/form-data（文件上传）
        'rest_framework.parsers.FileUploadParser',     # 专门处理文件上传
    ],
    
    # 渲染器
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',       # JSON渲染器
        'rest_framework.renderers.BrowsableAPIRenderer', # 浏览器API渲染器
        'rest_framework.renderers.AdminRenderer',      # Admin渲染器
    ],
    
    # 搜索参数
    'SEARCH_PARAM': 'search',
    'ORDERING_PARAM': 'ordering',
    
    # 过滤后端
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # Django过滤器
        'rest_framework.filters.SearchFilter',                 # 搜索过滤器
        'rest_framework.filters.OrderingFilter',               # 排序过滤器
    ],
    
    # 版本控制
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1', 'v2'],
    'VERSION_PARAM': 'version',
    
    # 限流配置（可选）
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',   # 匿名用户限流
        'rest_framework.throttling.UserRateThrottle',   # 认证用户限流
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/hour',    # 匿名用户每小时100次
        'user': '10000/hour',   # 认证用户每小时1000次
    },
    
    # 内容协商
    'DEFAULT_CONTENT_NEGOTIATION_CLASS': 'rest_framework.negotiation.DefaultContentNegotiation',
    
    # 元数据
    'DEFAULT_METADATA_CLASS': 'rest_framework.metadata.SimpleMetadata',
    
    # 异常处理
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    
    # 测试相关
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'TEST_REQUEST_RENDERER_CLASSES': [
        'rest_framework.renderers.MultiPartRenderer',
        'rest_framework.renderers.JSONRenderer',
    ],
    
    # URL格式
    'URL_FORMAT_OVERRIDE': 'format',
    
    # 格式后缀
    'FORMAT_SUFFIX_KWARG': 'format',
    
    # 分页参数名
    'PAGE_SIZE_QUERY_PARAM': 'page_size',
    'MAX_PAGE_SIZE': 100,
    
    # 日期时间格式
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'TIME_FORMAT': '%H:%M:%S',
    
    # 输入输出编码
    'UNICODE_JSON': True,
    'COMPACT_JSON': False,
    'COERCE_DECIMAL_TO_STRING': True,
    
    # 上传文件处理
    'UPLOADED_FILES_USE_URL': True,
    'UPLOADED_FILES_ALLOWED_EXTENSIONS': ['.pdf', '.doc', '.docx'],
    'UPLOADED_FILES_MAX_SIZE': 10 * 1024 * 1024,  # 10MB
}
# CORS 配置
CORS_ALLOW_ALL_ORIGINS = True  # 开发阶段用，生产环境请限制来源

# CORS 配置
CORS_ALLOW_ALL_ORIGINS = True  # 开发阶段用，生产环境请限制来源

# ============================================
# 文件上传配置
# ============================================

# 文件存储基础URL（根据你的文件存储服务配置）
FILE_BASE_URL = 'http://localhost:9000/'  # MinIO默认地址

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Django文件上传大小限制
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# 允许的文件扩展名
ALLOWED_FILE_EXTENSIONS = ['.pdf', '.doc', '.docx']

# 文件上传临时目录
FILE_UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, 'temp')
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# 确保目录存在
os.makedirs(MEDIA_ROOT, exist_ok=True)
os.makedirs(FILE_UPLOAD_TEMP_DIR, exist_ok=True)

# 文件存储类型配置
FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'  # 本地存储
# 如果使用MinIO：'storages.backends.s3boto3.S3Boto3Storage'
# 如果使用OSS：需要安装django-aliyun-oss2-storage

# 文件服务配置
MINIO_ENDPOINT = 'localhost:9000'
MINIO_ACCESS_KEY = 'minioadmin'
MINIO_SECRET_KEY = 'minioadmin'
MINIO_USE_HTTPS = False
MINIO_BUCKET_NAME = 'announcements'