# Generated by Django 5.0.1 on 2025-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeInfo',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('trans_type', models.CharField(max_length=2)),
                ('trans_date', models.DateTimeField()),
                ('trans_money', models.DecimalField(decimal_places=0, max_digits=15)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'trade_info',
                'managed': False,
            },
        ),
    ]
