# Generated by Django 5.0.1 on 2025-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('menu_id', models.AutoField(db_comment='菜单id', primary_key=True, serialize=False)),
                ('menu_name', models.CharField(db_comment='菜单名称', max_length=50)),
                ('menu_url', models.CharField(blank=True, db_comment='菜单链接', max_length=200, null=True)),
                ('parent_id', models.IntegerField(blank=True, db_comment='父级菜单ID', null=True)),
                ('sort_order', models.IntegerField(db_comment='排序顺序')),
                ('remark', models.CharField(blank=True, db_comment='备注', max_length=200, null=True)),
            ],
            options={
                'db_table': 'sys_menu',
                'db_table_comment': '菜单信息表',
                'managed': False,
            },
        ),
    ]
