# Generated by Django 5.0.1 on 2025-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=18, unique=True)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
