# Generated by Django 5.0.1 on 2025-11-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
    ]
