# Generated by Django 5.2.8 on 2025-11-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_alter_userinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
    ]
