# Generated by Django 5.0.1 on 2025-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('role_id', models.AutoField(db_comment='角色编号', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_comment='角色名称', max_length=50)),
                ('description', models.CharField(blank=True, db_comment='描述', max_length=200, null=True)),
            ],
            options={
                'db_table': 'sys_role',
                'db_table_comment': '角色信息表',
                'managed': False,
            },
        ),
    ]
