# Generated by Django 5.0.1 on 2025-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('user_id', models.AutoField(db_comment='用户编号', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_comment='用户名', max_length=50)),
                ('pid', models.CharField(db_comment='身份证号', max_length=18, unique=True)),
                ('email', models.CharField(blank=True, db_comment='邮箱', max_length=100, null=True)),
                ('mobile', models.CharField(db_comment='联系电话', max_length=20, unique=True)),
                ('address', models.CharField(blank=True, db_comment='居住地址', max_length=200, null=True)),
                ('password', models.CharField(db_comment='密码', max_length=100)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='修改时间', null=True)),
            ],
            options={
                'db_table': 'sys_user',
                'db_table_comment': '用户信息表',
                'managed': False,
            },
        ),
    ]
