# Generated by Django 5.0.1 on 2025-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('card_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cur_type', models.CharField(max_length=3)),
                ('open_date', models.DateTimeField()),
                ('open_money', models.DecimalField(decimal_places=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=15)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'card_info',
                'managed': False,
            },
        ),
    ]
