# Generated by Django 5.2.8 on 2025-11-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardinfo',
            options={'verbose_name': '银行卡信息'},
        ),
    ]
