# Generated by Django 5.2.8 on 2025-11-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardinfo', '0002_alter_cardinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='customer_id',
            field=models.IntegerField(default=1, verbose_name='客户ID'),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='card_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='卡号'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='cur_type',
            field=models.CharField(choices=[('CNY', '人民币'), ('USD', '美元'), ('EUR', '欧元'), ('JPY', '日元')], default='CNY', max_length=3, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开户日期'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='open_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='开户金额'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='password',
            field=models.CharField(default='123456', max_length=128, verbose_name='密码'),
        ),
    ]
