# Generated by Django 5.2.8 on 2025-11-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardinfo', '0003_cardinfo_customer_id_cardinfo_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='card_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='卡号'),
        ),
    ]
